name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # Run the job directly within the official Playwright image
    container:
      image: mcr.microsoft.com/playwright:v1.61.1-noble

    steps:
    # Clone current repositories with playwright tests
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Clone repository with software under testing
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: "Johnny-Fingers/node-react-real-world-example-app"
        path: app-repo

    # Configure pnpm
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 11.8.0
    
    # Get the cache route inside the container  
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV
    
    # Cache pnpm modules to speed up future pushes
    - name: Cache pnpm module
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    
    # Install testing dependencies
    - name: Install testing dependencies
      run: pnpm install --frozen-lockfile

    #Install application dependencies
    - name: Install application dependencies
      run: |
        cd app-repo
        npm ci
    
    # Run app with npm
    - name: Start Application Servers
      env:
        PORT: 3001
      run: |
        cd app-repo
        npm run dev &
        echo "Waiting for the local servers start up..."
        npx wait-on tcp:3001 tcp:5173 --timeout 60000

    # Run tests
    - name: Run Playwright tests
      env:
        HOME: /root
        CI: "true"
      run: pnpm test:all
    
    # Saving report is something fails
    - name: Upload test report on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-failure-report
        path: playwright-report/
        retention-days: 7